stages:  
  - build  
  - deploy

build_dev:  
  image: node:latest
  stage: build  
  only:
    - develop
  environment:
    name: dev
  variables:
    APP_NAME: '"Hypha DAO"'
    NETWORK_HOST: '"test.telos.kitchen"'
    NETWORK_PROTOCOL: '"https"'
    NETWORK_PORT: '443'
    SMARTCONTRACT: '"hyphadaomain"'
    TRAILCONTRACT: '"trailservice"'
    REGISTER_API_URL: '"https://opqeierg9e.execute-api.us-east-1.amazonaws.com/dev"'
    ACCOUNT_API_URL: '"https://opqeierg9e.execute-api.us-east-1.amazonaws.com/dev/v1/accounts"'
    BLOCKCHAIN_EXPLORER: '"https://telos-test.bloks.io"'
    PPP_ENV: '"test"'
  cache:
    paths:
      - node_modules/
  script:    
    - yarn global add @vue/cli@latest    
    - yarn install    
    - mv src/statics/chain-manifests-dev.json src/chain-manifests.json 
    - mv src/statics/app-metadata.json src/app-metadata.json
    - mv src/statics/app-manifest.json src/app-manifest.json
    - yarn build  
  artifacts:    
    paths:      
      - dist/    
    expire_in: 1 hour

deploy_dev:  
  image: python:latest  
  stage: deploy  
  only:    
    - develop  
  environment:
    name: dev
  script:    
    - pip install awscli    
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID_DEV
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_DEV
    - aws s3 rm s3://hypha-dapp-test
    - aws s3 sync ./dist/spa s3://hypha-dapp-test
    - aws s3 rm s3://dao-dev.hypha.earth
    - aws s3 sync ./dist/spa s3://dao-dev.hypha.earth
    # - aws cloudfront create-invalidation --distribution-id $AWS_DIST_ID_DEV --paths "/*"

