stages:
  - build
  - deploy

build_dev:
  image: node:latest
  stage: build
  only:
    - develop
  environment:
    name: dev
  variables:
    APP_NAME: '"Hypha DAO"'
    NETWORK_HOST: '"test.telos.kitchen"'
    NETWORK_PROTOCOL: '"https"'
    NETWORK_PORT: '443'
    SMARTCONTRACT: '"dao.hypha"'
    TRAILCONTRACT: '"trailservice"'
    REGISTER_API_URL: '"https://opqeierg9e.execute-api.us-east-1.amazonaws.com/dev"'
    ACCOUNT_API_URL: '"https://opqeierg9e.execute-api.us-east-1.amazonaws.com/dev/v1/accounts"'
    BLOCKCHAIN_EXPLORER: '"https://telos-test.bloks.io"'
    PPP_ENV: '"test"'
    SENTRY_DSN: '"https://6fa219bfb2ed453fb5032d6ce1b83fc9@sentry.io/1884471"'
    SENTRY_ENV: '"dev"'
  cache:
    paths:
      - node_modules/
  script:
    - yarn global add @vue/cli@latest
    - yarn install
    - mv src/statics/chain-manifests-dev.json src/statics/chain-manifests.json
    - mv src/statics/app-manifest-dev.json src/statics/app-manifest.json
    - yarn build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

deploy_dev:
  image: python:latest
  stage: deploy
  only:
    - develop
  environment:
    name: dev
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_KEY
    - aws configure set aws_secret_access_key $AWS_SECRET
    - aws s3 rm s3://dao-dev.hypha.earth
    - aws s3 sync ./dist/spa s3://dao-dev.hypha.earth
    - aws cloudfront create-invalidation --distribution-id $AWS_DIST_ID --paths "/*"

build_prod:
  image: node:latest
  stage: build
  only:
    - master
  environment:
    name: prod
  variables:
    APP_NAME: '"Hypha DAO"'
    NETWORK_HOST: '"api.telos.kitchen"'
    NETWORK_PROTOCOL: '"https"'
    NETWORK_PORT: '443'
    SMARTCONTRACT: '"dao.hypha"'
    TRAILCONTRACT: '"trailservice"'
    ACCOUNT_API_URL: '"https://tb3nnn0qa9.execute-api.us-east-1.amazonaws.com/prod/v1/accounts"'
    REGISTER_API_URL: '"https://tb3nnn0qa9.execute-api.us-east-1.amazonaws.com/prod"'
    BLOCKCHAIN_EXPLORER: '"https://telos.bloks.io"'
    PPP_ENV: '"prod"'
    SENTRY_DSN: '"https://6fa219bfb2ed453fb5032d6ce1b83fc9@sentry.io/1884471"'
    SENTRY_ENV: '"prod"'
  cache:
    paths:
      - node_modules/
  script:
    - yarn global add @vue/cli@latest
    - yarn install
    - mv src/statics/chain-manifests-prod.json src/statics/chain-manifests.json
    - mv src/statics/app-manifest-prod.json src/statics/app-manifest.json
    - yarn build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

deploy_prod:
  image: python:latest
  stage: deploy
  only:
    - master
  environment:
    name: prod
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_KEY
    - aws configure set aws_secret_access_key $AWS_SECRET
    - aws s3 rm s3://dao.hypha.earth
    - aws s3 sync ./dist/spa s3://dao.hypha.earth
    - aws cloudfront create-invalidation --distribution-id $AWS_DIST_ID --paths "/*"
